Nytt bloginnlegg
felleslosninger/devops.digdir.no pull request #6
Opened 2022-03-23 14:22 UTC by TheHydrogen3

2022-03-24 17:52 UTC, jmmucha requested changes

2022-03-24 17:52 UTC, jmmucha commented on content/bloggarkiv/vel-gjennomførte-devopsdagar/index.md
> +title: "Vel Gjennomførte DigdirDevOpsDagar"
Endre til "Vel gjennomførte Digdir DevOpsDagar"

2022-03-24 17:52 UTC, jmmucha commented on content/bloggarkiv/vel-gjennomførte-devopsdagar/index.md
> +ingress: Korleis gjekk det på DigdirDevOpsDagane, og korleis skal vi bygge devops kultur vidare?
Digdir DevOpsDagane
så devops-kultur

2022-03-24 17:52 UTC, jmmucha commented on content/bloggarkiv/vel-gjennomførte-devopsdagar/index.md
> +Då var dei første DigdirDevOpsDagane ferdige, og ut ifrå «measurement’sa» kan ein lese at det har vore ein strålande suksess. Der er sjølvsagt nokre forbetringspunkt, men det er slik det skal vere i
Digdir DevOpsDagane

Som nevnt før, ta vekk "measurement'sa" og erstatt med noe annet type tilbakemeldinger etc.

2022-03-24 17:52 UTC, jmmucha commented on content/bloggarkiv/vel-gjennomførte-devopsdagar/index.md
> +Første dagen gjekk stort sett med til å bli betre kjende med dei forskjellige teama i Digdir og korleis dei jobbar med DevOps i dag.
Kanskje du kunne skrive litt mer om dag 1? Kunne fortalt litt om målingene og forberedelser teamene hadde gjort. Kanskje vise til veggen vi hadde laget , den hadde vært fint å vise fram.

Skriv og gjerne hvor mange som deltok og hvor var dagene i år.

2022-03-24 17:52 UTC, jmmucha commented on content/bloggarkiv/vel-gjennomførte-devopsdagar/index.md
> +Den andre dagen var meir fagleg retta med diverse innlegg om DevOps kultur og teknologiar. Alexander Lystad frå Visma heldt eit foredrag om eit forskingsprosjekt Visma har gjennomført for å undersøke
devops-kultur
"prosessen å få ein feature ut i produksjon...." på 30min.

2022-03-24 17:52 UTC, jmmucha commented on content/bloggarkiv/vel-gjennomførte-devopsdagar/index.md
> +Den tredje dagen var vi på kontoret på Leikanger, der fortsette vi med litt opne diskusjonar.
Her var det og litt tynt. Kanskje skrive litt mer om hva som ble gjort på dag 3?

2022-03-24 17:52 UTC, jmmucha commented on content/bloggarkiv/vel-gjennomførte-devopsdagar/index.md
> +No har vi altso tatt eit steg vidare med å bygge DevOps kultur i Digdir, men kultur blir ikkje bygd på tre dagar. So kva skal vi gjere for å fortsette prosessen? Eit resultat av diskusjonane tredje d
devops-kultur

2022-03-24 17:52 UTC, jmmucha commented on content/bloggarkiv/vel-gjennomførte-devopsdagar/index.md
> +No har vi altso tatt eit steg vidare med å bygge DevOps kultur i Digdir, men kultur blir ikkje bygd på tre dagar. So kva skal vi gjere for å fortsette prosessen? Eit resultat av diskusjonane tredje d
frivillige bytte ut med entusiaster/interesserte

2022-03-28 19:51 UTC, jaflaten reviewed
LGTM. @jmmucha  får godkjenne

2022-03-28 20:05 UTC, jmmucha requested changes

2022-03-28 20:05 UTC, jmmucha commented on content/bloggarkiv/vel-gjennomførte-devopsdagar/index.md
> +title: "Vel Gjennomførte Digdir DevOpsDagar"
gjennomførte

2022-03-28 20:05 UTC, jmmucha commented on content/bloggarkiv/vel-gjennomførte-devopsdagar/index.md
> +Då var dei første Digdir DevOpsDagane ferdige, og ut ifrå "målingane" kan ein lese at det har vore ein strålande suksess. Der er sjølvsagt nokre forbetringspunkt, men det er slik det skal vere i DevO
bytt ut målingene med tilbakemeldingene

2022-03-29 07:54 UTC, jmmucha approved these changes

2022-03-29 11:34 UTC, merged